[package]
name = "unity3drs"
version = "0.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
libc = "0.2.137"
libloading = "0.7.4"
